### ISSUE TITLE
Item Details Layout 2 Issues

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/eventsManualPlugin#16]
- Image carousel should be square so that the circle doesn’t get cut off
- Overlay text should pull from Title Bar Text
- Map should be 16x9 ratio
- Address should be clickable, it should pull from primary links and buttons, and it should be centered with a dividing line underneath it like in the original mockup

Here's what it looks like:
<img width="360" alt="screen shot 2015-10-14 at 12 51 45 am" src="https://cloud.githubusercontent.com/assets/6145369/10477964/209b7f7a-720f-11e5-8575-1740a06dc1fa.png">
<img width="365" alt="screen shot 2015-10-14 at 12 51 57 am" src="https://cloud.githubusercontent.com/assets/6145369/10477966/233bddec-720f-11e5-8545-209b1e6c3bfb.png">

Here's what it should look like:
![event item layout 2](https://cloud.githubusercontent.com/assets/6145369/10477969/2f08773e-720f-11e5-8693-2dccbb965baf.png)

**Comment by kmtabish** [comment]
Fixed point 2 and 4. Please review.

@jdm135 Need your help for :- 
* Image carousel should be square so that the circle doesn’t get cut off
* Map should be 16x9 ratio

**Comment by jdm135** [comment]
@kmtabish If you want the image carousel to be a square, put a square image instead of a 16:9 image. Should be using cloudimage.io to crop these images. Crop it to a square.

Map should be 16x9, then decrease the height of the google map iframe to be shorter.

**Comment by sakshityagi** [comment]
@jdm135 decreasing height of the iframe, still shows black area under it.

**Comment by sakshityagi** [comment]
Also the height of the carousel images in not configurable by us.It gets it from carousel component of buildfire We tried giving our own style but didn't work.

**Comment by jdm135** [comment]
@sakshityagi The black area under it is the parent div. Make sure the height of the parent div is the same as the height of the iframe.

As for as the carousel images, I will contact the dev who created it and see if we can pass the type (16:9, 4:3, 4:4, etc) as a parameter so we can have different types of the carousel.

**Comment by jdm135** [comment]
@sakshityagi The dev has updated the carousel component to now accept different layout styles.

https://github.com/BuildFire/sdk/wiki/BuildFire-Carousel-Component

There is WideScreen, Square, and Cinema. Please use Square for this plugin and let me know how it works.

**Comment by sakshityagi** [comment]
Okay , so black area under map is fixed now. 
@jdm135 But carousel "Square" property didn't work for us. Took latest pull of sdk and tried but didn't work.

**Comment by jdm135** [comment]
@sakshityagi Please try again. Make sure you have the latest version of the SDK. 

If you view this file, you should be able to search for 'WideScreen'. If you find it, you have the latest version and it should be working.

/scripts/buildfire/components/carousel/carousel.js

**Comment by kmtabish** [comment]
@jdm135 yes we have the latest version of sdk and i searched in carousal.js file 'WideScreen' is there. but its still not working. I debug this and found that on the second call of 'this._initDimensions(layout)' method from the line 332 the 'layout' is going as 'undefined'. I think this is the issue.

**Comment by jdm135** [comment]
@kmtabish Oh ok. I'll ping the developer and try to have this resolved. Thanks.

**Comment by ahmadhmoud** [comment]
@sakshityagi @kmtabish
the issue of the carousel doesn't appear for me
I have tested it under this account
username: ahmed@hmoud.com
password: ahmed@hmoud.com
plugin name: Hmoud 12.1
please have a look and let me know if it helps you or not

**Comment by kmtabish** [comment]
@ahmadhmoud @jdm135  Thanks. we have to pass the style in 'view.loadItems()' also.
 @nathankeating Fixed. Please review.

**Comment by nathankeating** [comment]
Please make sure that the circle is centered and bigger. Review the high fidelity again.

**Comment by nathankeating** [comment]
Also, the overlay bar is not pulling from the title bar color.

**Comment by jdm135** [comment]
@kmtabish Please reference the themes documentation to add the proper classes on these elements. I believe the class is 'titleBarBackgroundTheme'. Add it to info-bar and remove any classes that were added for the blue primary color. 

http://int2.myapp.buildfire.com/styles/theme.html

**Comment by kmtabish** [comment]
@jdm135 I applied the given css classes but its not changing. I think these classes are not exiting in sdk.

**Comment by jdm135** [comment]
@kmtabish Make sure appTheme.css is being loaded dynamically. I might have an idea on why it's not working. Can you tell me if appTheme is being loaded in your app?

**Comment by kmtabish** [comment]
@jdm135 Yes its loaded, but in response it is showing '/*css cannot be rendered*/'.
